import { join } from "node:path";
import { access, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { launchVerifierTerminal, killVerifierTerminal } from "./launcher.js";
import type { VerifierState } from "./types.js";

export interface VerifierSpawnDeps {
  state: VerifierState;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", String.raw`'\''`)}'`;
}

async function buildWrapperScript(opts: {
  port: number;
  scriptPath: string;
  sessionId: string;
}): Promise<{ wrapperPath: string; stderrLogPath: string }> {
  const { port, scriptPath, sessionId } = opts;
  const wrapperPath = join(tmpdir(), `pi-verifier-${sessionId}.spawn.sh`);
  const stderrLogPath = join(tmpdir(), `pi-verifier-${sessionId}.stderr.log`);

  const wrapper = [
    "#!/usr/bin/env bash",
    "# Auto-generated by pi-verifier launcher",
    `STDERR_LOG=${shellQuote(stderrLogPath)}`,
    ': > "$STDERR_LOG"',
    `export PI_VERIFIER_PORT=${shellQuote(String(port))}`,
    `node ${shellQuote(scriptPath)} 2> >(tee -a "$STDERR_LOG" >&2)`,
    "EXIT_CODE=$?",
    'echo "" >> "$STDERR_LOG"',
    'echo "[wrapper] verifier exited with code $EXIT_CODE" >> "$STDERR_LOG"',
    "exit $EXIT_CODE",
    "",
  ].join("\n");

  await writeFile(wrapperPath, wrapper, { encoding: "utf8", mode: 0o700 });
  return { wrapperPath, stderrLogPath };
}

export async function startVerifier(deps: VerifierSpawnDeps): Promise<void> {
  const { state } = deps;
  const sessionId = state.verifierSessionId;
  if (!sessionId) {
    state.lastContext?.ui.notify(
      "[pi-verifier] No session ID available. Start a PI session first.",
      "warning",
    );
    return;
  }

  const scriptPath = join(import.meta.dirname, "verifier.js");

  // Verify the compiled verifier script exists before spawning
  try {
    await access(scriptPath);
  } catch {
    state.lastContext?.ui.notify(
      `[pi-verifier] Verifier script not found: ${scriptPath}. Run "pnpm run build" first.`,
      "error",
    );
    return;
  }

  const { wrapperPath, stderrLogPath } = await buildWrapperScript({
    port: state.port,
    scriptPath,
    sessionId,
  });

  try {
    const result = await launchVerifierTerminal({
      sessionId,
      verifierCommand: `bash ${wrapperPath}`,
    });
    state.lastContext?.ui.notify(
      `[pi-verifier] Verifier launched in tmux session: ${result.tmuxSession}. Use /verify launch to attach.`,
      "info",
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    let detail = message;
    // Try to read stderr log for the real cause
    try {
      const { readFile } = await import("node:fs/promises");
      const stderr = await readFile(stderrLogPath, "utf8");
      if (stderr.trim()) {
        const lastLine = stderr.trim().split("\n").pop() ?? stderr.trim();
        detail += ` | verifier stderr: ${lastLine}`;
      }
    } catch {
      // log not readable yet
    }
    state.lastContext?.ui.notify(`[pi-verifier] Failed to launch verifier: ${detail}`, "error");
    state.mode = "waiting";
  }
}

export function stopVerifier(deps: VerifierSpawnDeps): void {
  const { state } = deps;
  const sessionId = state.verifierSessionId;
  if (sessionId) {
    void killVerifierTerminal(sessionId);
  }
  state.verifierSessionId = undefined;
}
