import { join } from "node:path";
import { access, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { launchVerifierTerminal, killVerifierTerminal } from "./launcher.js";
import type { VerifierState } from "./types.js";

export interface VerifierSpawnDeps {
  state: VerifierState;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", String.raw`'\''`)}'`;
}

async function buildWrapperScript(opts: {
  port: number;
  scriptPath: string;
  sessionId: string;
}): Promise<{ wrapperPath: string; stderrLogPath: string }> {
  const { port, scriptPath, sessionId } = opts;
  const wrapperPath = join(tmpdir(), `pi-verifier-${sessionId}.spawn.sh`);
  const stderrLogPath = join(tmpdir(), `pi-verifier-${sessionId}.stderr.log`);

  const nodeCommand = buildNodeCommand(scriptPath);

  const wrapper = [
    "#!/usr/bin/env bash",
    "# Auto-generated by pi-verifier launcher",
    `STDERR_LOG=${shellQuote(stderrLogPath)}`,
    ': > "$STDERR_LOG"',
    `export PI_VERIFIER_PORT=${shellQuote(String(port))}`,
    `${nodeCommand} 2> >(tee -a "$STDERR_LOG" >&2)`,
    "EXIT_CODE=$?",
    'echo "" >> "$STDERR_LOG"',
    'echo "[wrapper] verifier exited with code $EXIT_CODE" >> "$STDERR_LOG"',
    "exit $EXIT_CODE",
    "",
  ].join("\n");

  await writeFile(wrapperPath, wrapper, { encoding: "utf8", mode: 0o700 });
  return { wrapperPath, stderrLogPath };
}

async function resolveVerifierScript(): Promise<string | undefined> {
  const candidates = [
    // Standard: running from dist/ — verifier.js is in the same dir
    join(import.meta.dirname, "verifier.js"),
    // Dev mode: running from src/ via tsx/ts-node — compiled output is in ../dist/
    join(import.meta.dirname, "..", "dist", "verifier.js"),
    // Fallback: running from dist/ but verifier.ts is in ../src/ (tsx handles .ts)
    join(import.meta.dirname, "..", "src", "verifier.ts"),
    // Fallback: running from src/ with tsx — use the .ts directly
    join(import.meta.dirname, "verifier.ts"),
  ];

  const checks = candidates.map(async (p) => {
    await access(p);
    return p;
  });

  try {
    return await Promise.any(checks);
  } catch {
    return undefined;
  }
}

function buildNodeCommand(scriptPath: string): string {
  if (scriptPath.endsWith(".ts")) {
    // Try tsx first, then ts-node, then plain node (if tsx is installed globally)
    return `tsx ${scriptPath}`;
  }
  return `node ${scriptPath}`;
}

export async function startVerifier(deps: VerifierSpawnDeps): Promise<void> {
  const { state } = deps;
  const sessionId = state.verifierSessionId;
  if (!sessionId) {
    state.lastContext?.ui.notify(
      "[pi-verifier] No session ID available. Start a PI session first.",
      "warning",
    );
    return;
  }

  const scriptPath = await resolveVerifierScript();

  if (!scriptPath) {
    state.lastContext?.ui.notify(
      `[pi-verifier] Verifier script not found. Tried:\n${[
        join(import.meta.dirname, "verifier.js"),
        join(import.meta.dirname, "..", "dist", "verifier.js"),
        join(import.meta.dirname, "..", "src", "verifier.ts"),
        join(import.meta.dirname, "verifier.ts"),
      ]
        .map((p) => `  - ${p}`)
        .join("\n")}\n\nRun "pnpm run build" first.`,
      "error",
    );
    return;
  }

  const { wrapperPath, stderrLogPath } = await buildWrapperScript({
    port: state.port,
    scriptPath,
    sessionId,
  });

  try {
    const result = await launchVerifierTerminal({
      sessionId,
      verifierCommand: `bash ${wrapperPath}`,
    });
    state.lastContext?.ui.notify(
      `[pi-verifier] Verifier launched in tmux session: ${result.tmuxSession}. Use /verify launch to attach.`,
      "info",
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    let detail = message;
    // Try to read stderr log for the real cause
    try {
      const { readFile } = await import("node:fs/promises");
      const stderr = await readFile(stderrLogPath, "utf8");
      if (stderr.trim()) {
        const lastLine = stderr.trim().split("\n").pop() ?? stderr.trim();
        detail += ` | verifier stderr: ${lastLine}`;
      }
    } catch {
      // log not readable yet
    }
    state.lastContext?.ui.notify(`[pi-verifier] Failed to launch verifier: ${detail}`, "error");
    state.mode = "waiting";
  }
}

export function stopVerifier(deps: VerifierSpawnDeps): void {
  const { state } = deps;
  const sessionId = state.verifierSessionId;
  if (sessionId) {
    void killVerifierTerminal(sessionId);
  }
  state.verifierSessionId = undefined;
}
